name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11] # Test across multiple Python versions

    steps:
      # Step 1: Checkout the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml

      # Step 5: Check formatting (optional)
      - name: Check code formatting with black
        run: |
          pip install black
          black --check .

      # Step 6: Build package
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      # Step 7: Upload test results (optional)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: junit/test-results.xml

      # Step 8: Upload built package (optional)
      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
